GET http://127.0.0.1:8080/users/100/jack HTTP/1.1


### params:路径参数
GET http://127.0.0.1:8080/userinfo/100/cid/1000 HTTP/1.1

### get:传参
GET http://127.0.0.1:8080/get?pid=1&username=jack HTTP/1.1


### urlencoded:编码的数据传参
### 必须设置:Content-Type: application/x-www-form-urlencoded
POST http://127.0.0.1:8080/urlencoded HTTP/1.1
Content-Type: application/x-www-form-urlencoded

a=1&b=2&c=3


### json:json传参
### 必须设置:Content-Type: application/json
POST http://127.0.0.1:8080/json HTTP/1.1
Content-Type: application/json

{"name":"jiack","age":18}


### header:header传参
### 必须设置:Content-Type: application/json
POST http://127.0.0.1:8080/header HTTP/1.1
test:'hahah'
username:'jack'
age:18